before_install:
  - gem update --system
  - gem update bundler
script: 'rspec spec'
notifications:
  email:
    - john.crepezzi@gmail.com
branches:
  only:
    - master
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
